/*
 * tiny-thermal-sr full-INT8 benchmark: edsr_tiny on ESP32 / Raspberry Pi Pico.
 * Auto-generated by measure/make_firmware.py - do not edit by hand.
 *
 * LR 32x24 -> SR 64x48, int8 input/output, MLX90640 test frame embedded.
 * Prints CAS:key=value lines at 115200 baud.
 */

#include <Arduino.h>
#if defined(ARDUINO_ARCH_ESP32)
#include <esp_heap_caps.h>
#else
#include <TensorFlowLiteMicro.h>
#endif

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "edsr_tiny_int8_data.h"
#include "test_image.h"

constexpr int kBenchmarkSamples = 10;
constexpr size_t kMaxArena = 144 * 1024;

#if defined(ARDUINO_ARCH_ESP32)
static uint8_t* tensor_arena = nullptr;
static size_t arena_size = 0;

static void allocate_arena() {
    size_t candidate = kMaxArena;
    while (candidate >= 16 * 1024) {
        tensor_arena = static_cast<uint8_t*>(
            heap_caps_malloc(candidate, MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT));
        if (tensor_arena != nullptr) {
            arena_size = candidate;
            return;
        }
        candidate -= 16 * 1024;
    }
}

static long free_mem() {
    return (long)heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
}
static const char* kBoard = "esp32";
#else
alignas(16) static uint8_t tensor_arena[kMaxArena];
static size_t arena_size = kMaxArena;
static void allocate_arena() {}

static long free_mem() {
#if defined(ARDUINO_ARCH_RP2040)
    return (long)rp2040.getFreeHeap();
#else
    return -1;
#endif
}
static const char* kBoard = "pico";
#endif

void setup() {
    Serial.begin(115200);
    delay(2000);
    Serial.println();
    Serial.println("CAS:begin");
    Serial.printf("CAS:model=edsr_tiny\n");
    Serial.printf("CAS:board=%s\n", kBoard);
    Serial.printf("CAS:model_bytes=%u\n",
                  (unsigned)edsr_tiny_int8_tflite_len);

    long heap_before = free_mem();
    Serial.printf("CAS:heap_before=%ld\n", heap_before);

    allocate_arena();
    if (tensor_arena == nullptr) {
        Serial.println("CAS:status=NOFIT_ARENA_ALLOC");
        return;
    }
    Serial.printf("CAS:arena_alloc=%u\n", (unsigned)arena_size);

    const tflite::Model* model = tflite::GetModel(edsr_tiny_int8_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("CAS:status=ERR_SCHEMA");
        return;
    }

    tflite::MicroMutableOpResolver<3> resolver;
    resolver.AddAdd();
    resolver.AddConv2D();
    resolver.AddDepthToSpace();

    tflite::MicroInterpreter interpreter(model, resolver,
                                         tensor_arena, arena_size);
    if (interpreter.AllocateTensors() != kTfLiteOk) {
        Serial.printf("CAS:arena_alloc=%u\n", (unsigned)arena_size);
        Serial.println("CAS:status=NOFIT_TENSORS");
        return;
    }
    Serial.printf("CAS:arena_used=%u\n",
                  (unsigned)interpreter.arena_used_bytes());
    Serial.printf("CAS:heap_after=%ld\n", free_mem());

    TfLiteTensor* input = interpreter.input(0);
    TfLiteTensor* output = interpreter.output(0);
    if (input->type != kTfLiteInt8 || output->type != kTfLiteInt8) {
        Serial.println("CAS:status=ERR_NOT_INT8_IO");
        return;
    }
    const int in_len = kTestInputHeight * kTestInputWidth;
    const int out_len = kTestOutputHeight * kTestOutputWidth;
    if ((int)input->bytes != in_len || (int)output->bytes != out_len) {
        Serial.printf("CAS:status=ERR_SHAPE in=%d out=%d\n",
                      (int)input->bytes, (int)output->bytes);
        return;
    }

    memcpy(input->data.int8, test_input_int8, in_len);

    unsigned long t0 = micros();
    if (interpreter.Invoke() != kTfLiteOk) {
        Serial.println("CAS:status=ERR_INVOKE");
        return;
    }
    Serial.printf("CAS:invoke_us_first=%lu\n", micros() - t0);

    // Bit-exactness vs the PC TFLite interpreter output.
    int mismatches = 0;
    int max_abs_diff = 0;
    for (int i = 0; i < out_len; i++) {
        int diff = (int)output->data.int8[i] - (int)reference_output_int8[i];
        if (diff < 0) diff = -diff;
        if (diff > 0) mismatches++;
        if (diff > max_abs_diff) max_abs_diff = diff;
    }
    Serial.printf("CAS:ref_mismatches=%d\n", mismatches);
    Serial.printf("CAS:ref_max_abs_diff=%d\n", max_abs_diff);

    // Timed samples (input refilled each run; output overwritten in place).
    for (int s = 0; s < kBenchmarkSamples; s++) {
        memcpy(input->data.int8, test_input_int8, in_len);
        unsigned long ts = micros();
        interpreter.Invoke();
        Serial.printf("CAS:sample_us=%lu\n", micros() - ts);
    }

    // SR output dump for qualitative figures (int8 values, row-major).
    Serial.print("CAS:sr_int8=");
    for (int i = 0; i < out_len; i++) {
        Serial.print((int)output->data.int8[i]);
        if (i < out_len - 1) Serial.print(",");
    }
    Serial.println();

    Serial.println("CAS:status=OK");
    Serial.println("CAS:end");
}

void loop() {}
